package:
  name: divvier
  version: 1.12

source:
  path: ../../lib/Divvier

build:
  number: 3

requirements:
  build:
    - {{ compiler('c') }}

about:
  summary: This is a simple meta-package
  license: GPL