package:
  name: phylofisher
  version: 0.1

build:
  number: 4

  ignore_prefix_files:
    - example/
    - docs/
    - distribution/
    - .gitignore
    - README.md

requirements:
  run:
    - python=3
    - trimal
    - raxml
    - biopython
    - hmmer
    - pyqt
    - ete3
    - diamond
    - pandas
    - matplotlib
    - fasttree
    - blast
    - cd-hit
    - mafft
    - setuptools

about:
  summary: This is a simple meta-package
  license: MIT