package:
  name: noodler
  version: 0.1

source:
 git_url: https://github.com/Seraff/svgPhyloTreeCheckboxer.git

build:
  number: 2

requirements:
  run:
    - nodejs

about:
  home: https://github.com/Seraff/svgPhyloTreeCheckboxer