package:
  name: dist_est
  version: 1.1
source:
    path: ../../../lib/dist_estv1.1

build:
  number: 0

about:
    summary: Estimation of Rates-Across-Sites Distributions in Phylogenetic Subsititution Models
extra:
    copy_test_source_files: true
    final: true