package:
  name: dist_est
  version: 1.1

source:
  path: ../dist_estv1.1

build:
  number: 7

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('gfortran') }}
  host:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('gfortran') }}
  run:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('gfortran') }}

about:
    home: https://www.mathstat.dal.ca/~tsusko/doc/ras.pdf
    summary: Estimation of Rates-Across-Sites Distributions in Phylogenetic Subsititution Models
