package:
  name: prequal
  version: 1.02
source:
    path: ../../lib/prequal
test:
    commands:
        - prequal | grep prequal > /dev/null
about:
    home: https://github.com/simonwhelan/prequal
    license: GNU General Public v3 or later (GPLv3+)
    license_family: GPL3
    license_file: LICENSE
    summary: a pre-alignment quality filter for comparative sequence analyses
extra:
    copy_test_source_files: true
    final: true