package:
  name: phylofisher
  version: 0.1.20

source:
  path: ../../

build:
  number: 1
  script:
    - python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - setuptools

  run:
    # Python Deps
    - python=3.7
    - biopython=1.76
    - pyqt=5.9.2
    - ete3=3.1.1
    - pandas=1.0.1
    - matplotlib=3.2.1
    # NON-Python Deps
    - binutils=2.34
    - trimal=1.4.1
    - raxml=8.2.12
    - hmmer=3.3
    - diamond=0.9.36
    - fasttree=2.1.10
    - blast=2.9.0
    - cd-hit=4.8.1
    - mafft=7.455
    - divvier=1.01
    - bmge=1.12
    - prequal=1.02
    - dist_est=1.1
    - astral=5.7.3

about:
  summary: PhyloFisher is a software package for the creation, analysis, and visualization of phylogenomic datasets that consist of protein sequences from eukaryotic organisms.
  license: MIT