{% set name = "phylofisher" %}
{% set version = "1.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - biopython
    - ete3
    - matplotlib
    - numpy
    - pandas
    - pip
    - pyqt
    - python
    - scipy
    - binutils
    - parasorter
    - trimal=1.4.1
    - raxml=8.2.12
    - hmmer=3.3
    - diamond=0.9.36
    - fasttree=2.1.10
    - blast=2.9.0
    - cd-hit=4.8.1
    - mafft=7.455
    - divvier=1.01
    - bmge=1.12
    - prequal=1.02
    - dist_est=1.1
    - astral=5.7.3
  run:
    - biopython
    - ete3
    - matplotlib
    - numpy
    - pandas
    - pyqt
    - python
    - scipy
    - binutils
    - parasorter
    - trimal=1.4.1
    - raxml=8.2.12
    - hmmer=3.3
    - diamond=0.9.36
    - fasttree=2.1.10
    - blast=2.9.0
    - cd-hit=4.8.1
    - mafft=7.455
    - divvier=1.01
    - bmge=1.12
    - prequal=1.02
    - dist_est=1.1
    - astral=5.7.3

test:
  imports:
    - phylofisher
    - phylofisher.utilities

about:
  home: "https://github.com/TheBrownLab/PhyloFisher"
  license: MIT
  license_family: MIT
  license_file: 
  summary: "PhyloFisher is a software package for the creation, analysis, and visualization of phylogenomic datasets that consist of protein sequences from eukaryotic organisms."
  doc_url: 
  dev_url: 

