{% set name = "phylofisher" %}
{% set version = "1.0.7" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: b782f19174eea33f6c4af97fad213e7051dd5463a142886746cae91c9c2bfca8

build:
  number: 3
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - biopython=1.78
    - ete3=3.1.2
    - matplotlib=3.4.1
    - numpy=1.20.2
    - pandas=1.2.4
    - pip=21.0.1
    - pyqt=5.12.3
    - python=3.7.10
    - scipy=1.6.2
    - binutils=1.0.1
    - parasorter
    - trimal=1.4.1
    - raxml=8.2.12
    - hmmer=3.3
    - diamond=0.9.36
    - fasttree=2.1.10
    - blast=2.9.0
    - cd-hit=4.8.1
    - mafft=7.455
    - divvier=1.01
    - bmge=1.12
    - prequal=1.02
    - dist_est=1.1
    - astral=5.7.3
  run:
    - biopython=1.78
    - ete3=3.1.2
    - matplotlib=3.4.1
    - numpy=1.20.2
    - pandas=1.2.4
    - pip=21.0.1
    - pyqt=5.12.3
    - python=3.7.10
    - scipy=1.6.2
    - binutils=1.0.1
    - parasorter
    - trimal=1.4.1
    - raxml=8.2.12
    - hmmer=3.3
    - diamond=0.9.36
    - fasttree=2.1.10
    - blast=2.9.0
    - cd-hit=4.8.1
    - mafft=7.455
    - divvier=1.01
    - bmge=1.12
    - prequal=1.02
    - dist_est=1.1
    - astral=5.7.3

test:
  imports:
    - phylofisher
    - phylofisher.utilities

about:
  home: "https://github.com/TheBrownLab/PhyloFisher"
  license: MIT
  license_family: MIT
  license_file: 
  summary: "PhyloFisher is a software package for the creation, analysis, and visualization of phylogenomic datasets that consist of protein sequences from eukaryotic organisms."
  doc_url: 
  dev_url: 

